Update to new project template

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,28 +1,19 @@
 stages:
   - lint
   - test
-  - docs-test
-  - docs-build
   - tag
-  - package
-
-workflow:
-  rules:
-    - if: $CI_COMMIT_BRANCH
-      when: always
-    - when: never
+  - publish
 
 variables:
   GIT_STRATEGY: clone
   IMAGE_NAME: ${NDIP_DOCKER_REPOSITORY}/${CI_PROJECT_PATH}
-
 
 before_script:
   - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
   - source rse-bash-modules.sh
   - func_rse_docker_cleanup
   - docker login -u $NDIP_DOCKER_USER -p $NDIP_DOCKER_PASSWORD $NDIP_DOCKER_REPOSITORY
-
+  - export VERSION=$(cat pyproject.toml | grep "version =" | head -n 1 | awk '{ print $3 }' | tr -d '"')
 after_script:
   - curl https://code.ornl.gov/rse-deployment/rse-sharables/raw/master/rse-bash-modules.sh -O
   - source rse-bash-modules.sh
@@ -61,48 +52,34 @@ unit-tests:
     - rse-multi-builder
 
 docs-test:
-  stage: docs-test
+  stage: test
   script:
-    - docker run -u `id -u`:`id -g` ${IMAGE_NAME}:src-${CI_COMMIT_SHA} poetry run sphinx-build -M html docs sphinx -W
+    - docker run -u `id -u`:`id -g` ${IMAGE_NAME}:src-${CI_COMMIT_SHA} bash build_docs.sh
   tags:
     - rse-multi-builder
 
-docs-build:
-  stage: docs-build
-  rules:
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
-      when: always
-    - when: manual
-  script:
-    - curl -X POST -d "branches=latest" -d "token=${READTHEDOCS_WEBHOOK_SECRET}" -d "default_branch=${CI_COMMIT_BRANCH}" ${READTHEDOCS_WEBHOOK_URL}
-  tags:
-    - rse-multi-builder
 
 tag-release:
   stage: tag
   rules:
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
       when: always
-    - when: manual
+    - when: never
   script:
     - git config user.email "$GITLAB_USER_EMAIL"
     - git config user.name "$GITLAB_USER_NAME"
-    - VERSION=$(cat pyproject.toml | grep "version =" | awk '{ print $3 }' | tr -d '"')
     - >
       if [ -z $(git ls-remote --tags origin "$VERSION") ]; then
-        git remote add gitlab https://oauth2:${TAG_PUSH_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
+        git remote add gitlab https://oauth2:${NDIP_GROUP_TOKEN}@${CI_SERVER_HOST}/${CI_PROJECT_PATH}.git
         git tag ${VERSION}
-        git push gitlab ${VERSION}
+        git push gitlab ${VERSION} --tags
       fi
   tags:
   - rse-multi-builder
 
+
 package-build:
-  stage: package
-  rules:
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
-      when: always
-    - when: manual
+  stage: publish
   script:
     - >
       docker run
@@ -110,8 +87,25 @@ package-build:
       ${IMAGE_NAME}:src-${CI_COMMIT_SHA}
       bash -c "
       poetry config repositories.gitlab_repo ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi &&
-      poetry publish --skip-existing -u gitlab-ci-token -p ${CI_JOB_TOKEN} -r gitlab_repo &&
-      poetry publish --skip-existing -u __token__ -p ${PYPI_API_TOKEN}
+      poetry publish -u gitlab-ci-token -p ${CI_JOB_TOKEN} -r gitlab_repo
+      poetry publish -u __token__ -p ${PYPI_API_TOKEN}
       "
+  when: manual
+  tags:
+    - rse-multi-builder
+
+docs-publish:
+  stage: publish
+  rules:
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
+      when: always
+    - when: manual
+  script:
+    - |
+      if [ -z "$READTHEDOCS_WEBHOOK_SECRET" ] || [ -z "$READTHEDOCS_WEBHOOK_URL" ]; then
+        echo "Error: READTHEDOCS_WEBHOOK_SECRET and/or READTHEDOCS_WEBHOOK_URL is not set."
+        exit 1
+      fi
+    - curl -X POST -d "branches=latest" -d "token=${READTHEDOCS_WEBHOOK_SECRET}" -d "default_branch=${CI_COMMIT_BRANCH}" ${READTHEDOCS_WEBHOOK_URL}
   tags:
     - rse-multi-builder
